### ISSUE TITLE
Latest V5 Css version?

### ISSUE THREAD

**Issue by bgarrant** [jacob418/kube#1]
Does this use the newest V5 version of Kube? I have been looking for a working Sass version. Any known issues?

**Comment by jacob418** [comment]
I only have found the v5.0 unfortunately. Is there a newer one?

I just started over and i was going to use it for creating a Theme for the Contao CMS.
Since I do exams at this time, I think I will not be able to work on it until 07/15/16.

Im just starting and i want to extend it with some basic stuff like menus, which actually where part of v4.
Also i want to keep it clean from javascript and im going to drop the less at the time i checkt if everything is portet to sass without problems.

I Guess making a list and put it to the readme would be a good idea.

For now i have found just 1 "serious" issue. The retina image mixing did use some special less function and so far i have not found any replacement. Its manipulating a source string for the image.

**Comment by jacob418** [comment]
I wrote everything to the Readme file. closing now.
